<?php

namespace Veml\TorzslapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Torzslap4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Torzslap4Repository extends EntityRepository
{
}