<?php

namespace Veml\TorzslapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Torzslap2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Torzslap2Repository extends EntityRepository
{
}