parameters:
#    veml_hello.example.class: Veml\HelloBundle\Example

services:
#    veml_hello.example:
#        class: %veml_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
